try:
  print(x)
except:
  print("S'ha produït una excepció!")
